#!/usr/bin/env bash
set -e

export TRIPLEO_ROOT=~/tripleo

if [ ! -d "$TRIPLEO_ROOT" ]; then
  mkdir $TRIPLEO_ROOT
fi

# make cloning inteligent (when git repo exists => pull)
declare -a GITHUB_REPOS=('tripleo/incubator' 'tripleo/bm_poseur' 'stackforge/diskimage-builder' 'stackforge/tripleo-image-elements');
for repo in "${GITHUB_REPOS[@]}"
do
  cd $TRIPLEO_ROOT
  repo_dir=${repo##*/}
  if [ -d "$repo_dir" ]; then
    set +e
    cd $repo_dir
    git status
    if [ "$?" == "0" ]; then
      git pull
    else
      cd $TRIPLEO_ROOT
      rm -rf $repo_dir
      git clone "https://github.com/${repo}"
    fi
    set -e
  else
    git clone "https://github.com/${repo}"
  fi
done

cd $TRIPLEO_ROOT/incubator
scripts/install-dependencies

# test for user's groups - it has to contain libvirtd
set +e
id | grep libvirtd
if [ "$?" != "0" ]; then
  echo "Please, log out and log in to be able to connect to libvirt"
  echo "and then run this script again"
  exit 1
fi
set -e

cd $TRIPLEO_ROOT/bm_poseur/
sudo ./bm_poseur --bridge-ip=none create-bridge

sudo service libvirt-bin restart

# FIXME: test for existing ssh public key

cd $TRIPLEO_ROOT/diskimage-builder/
bin/disk-image-create -u base -a i386 -o $TRIPLEO_ROOT/incubator/base

cd $TRIPLEO_ROOT/tripleo-image-elements/elements/boot-stack
sed -i "s/\"virtual_power_user\": \"stack\",/\"virtual_power_user\": \"`whoami`\",/" config.json

cd $TRIPLEO_ROOT/incubator/
scripts/boot-elements boot-stack -o bootstrap

BOOTSTRAP_IP=`scripts/get-vm-ip bootstrap`

sudo $TRIPLEO_ROOT/bm_poseur/bm_poseur --vms 1 --arch i686 create-vm

MAC=`$TRIPLEO_ROOT/bm_poseur/bm_poseur get-macs`

scp root@$BOOTSTRAP_IP:stackrc ~/stackrc
sed -i "s/localhost/$BOOTSTRAP_IP/" ~/stackrc
source ~/stackrc

nova keypair-add --pub-key ~/.ssh/id_rsa.pub default

nova baremetal-node-create ubuntu 1 512 10 $MAC

# Wait for the following to show up in the nova-compute log on the bootstrap node
# 2013-01-08 16:43:13 AUDIT nova.compute.resource_tracker [-] Auditing locally available compute resources
# 2013-01-08 16:43:13 DEBUG nova.compute.resource_tracker [-] Hypervisor: free ram (MB): 512 from (pid=24853) _report_hypervisor_resource_view /opt/stack/nova/nova/compute/resource_tracker.py:327
# 2013-01-08 16:43:13 DEBUG nova.compute.resource_tracker [-] Hypervisor: free disk (GB): 0 from (pid=24853) _report_hypervisor_resource_view /opt/stack/nova/nova/compute/resource_tracker.py:328
# 2013-01-08 16:43:13 DEBUG nova.compute.resource_tracker [-] Hypervisor: free VCPUs: 1 from (pid=24853) _report_hypervisor_resource_view /opt/stack/nova/nova/compute/resource_tracker.py:333
# 2013-01-08 16:43:13 AUDIT nova.compute.resource_tracker [-] Free ram (MB): 0
# 2013-01-08 16:43:13 AUDIT nova.compute.resource_tracker [-] Free disk (GB): 0
# 2013-01-08 16:43:13 AUDIT nova.compute.resource_tracker [-] Free VCPUS: 1

cd $TRIPLEO_ROOT/incubator/
scripts/load-image base.qcow2

ssh root@$BOOTSTRAP_IP "cat /opt/stack/boot-stack/virtual-power-key.pub" >> ~/.ssh/authorized_keys

nova boot --flavor 256 --image base --key_name default bmtest

